### ISSUE TITLE
disqus comments

### ISSUE THREAD

**Issue by HazemSamir** [TaylanTatli/Moon#26]
When I tried to run disqus comments on my blog, it did not work for me till I added this line to disqus_comments.html file after the if condition:

`<div id="disqus_thread"></div>`

And what about changing the default `disqus_shortname` in _config.yml to either be commented or be something dummy like `shortname` or so, instead of the author's `taylantatli`?

**Comment by TaylanTatli** [comment]
You done so much customizations on your site so i don't know what gone wrong about your comments but it's working on my site if I add `comments: true` to post's front matter. Also I looked others' blogs who forked this theme and it's working for them too. 

You are right about `disqus_shortname` but it's like that because I don't want to deal with both branches seperately just for `url` and `disqus_shortname` also it's self explanatory. But if you think it's confusing, I can change.

**Comment by libeclipse** [comment]
You're meant to register on Disqus and put that username as your username
for disqus in config.yml

**Comment by TaylanTatli** [comment]
Ah, I found it. It seems you removed 
```
{% if page.comments and site.disqus_shortname %}<section id="disqus_thread" class="animated fadeInUp"></section><!-- /#disqus_thread -->{% endif %}
```
this line from `_layouts/post.html` and `_layouts/page.html`. I should be like this: https://github.com/TaylanTatli/Moon/blob/master/_layouts/post.html#L41

**Comment by HazemSamir** [comment]
My bad, I am so sorry :smile: 

Concerning the shortname, it was just a suggestion not a big deal.

Thanks for the great theme
