### ISSUE TITLE
CSS not showing up correctly

### ISSUE THREAD

**Issue by MattBlanco** [TaylanTatli/Moon#77]
After following the setup guide, my site at [mattblanco.github.io](mattblanco.github.io) isn't showing the css correctly.

**Comment by tanto259** [comment]
Hi,
Can you try to edit your _config.yml file,
-  change the url to `https://mattblanco.github.io` (make sure it is using https)

and see if it works.

The problem could be caused by the site trying to serve the CSS from http://taylantatli.me/Moon (from the settings in the _config.yml file) which is unsecured through HTTPS.

Github Pages on the otherhand, force HTTPS through all users pages, creating a Mixed Content problem.

As a comparison, try to compare this:
[https://recruiter-dockings-58223.netlify.com/](https://recruiter-dockings-58223.netlify.com/)
and this:
[https://581363bdd6865d6b0a127553--recruiter-dockings-58223.netlify.com/](https://581363bdd6865d6b0a127553--recruiter-dockings-58223.netlify.com/)

Also, don't forget to
-  change the disqus_shortname to your site's (make one at [https://disqus.com/admin/
](https://disqus.com/admin/))
-  edit all the social account to your social account

**Comment by MattBlanco** [comment]
Yeah I had a different repo where I had changed the url  to the one you showed and the social accounts, but it was having the same issues so I wanted to try forking this one to find the problem.

**Comment by tanto259** [comment]
Hmm, I am not sure why your local repo isn't working. Personally, I never had any problems with cloning though.
